### ISSUE TITLE
AttributeError: module 'clingo.ast' has no attribute 'Transformer'

### ISSUE THREAD

**Issue by ArdalanKhazraei** [potassco/telingo#14]
Hello, 
 when I try to run telingo-related commands on the Anaconda command prompt, I get the message below. Would you know how to solve this problem? Thanks in advance.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\telingo-script.py", line 5, in <module>
    from telingo import main
  File "C:\Users\khazraei\AppData\Roaming\Python\Python37\site-packages\telingo\__init__.py", line 13, in <module>
    from . import transformers as _tf
  File "C:\Users\khazraei\AppData\Roaming\Python\Python37\site-packages\telingo\transformers\__init__.py", line 70, in <module>
    from . import program as _prg
  File "C:\Users\khazraei\AppData\Roaming\Python\Python37\site-packages\telingo\transformers\program.py", line 9, in <module>
    from . import term as _tt
  File "C:\Users\khazraei\AppData\Roaming\Python\Python37\site-packages\telingo\transformers\term.py", line 14, in <module>
    class TermTransformer(_ast.Transformer):
AttributeError: module 'clingo.ast' has no attribute 'Transformer'

**Comment by rkaminsk** [comment]
There was a bug in the telingo 2.1.0 release. I already published a bugfix release. You can update with
```sh
pip install --upgrade telingo clingo
```
